// components/Header.vue
<template>
  <header id="header">
    <ul class="menu">
      <li><nuxt-link to="/">Home</nuxt-link></li>
      <li><nuxt-link to="/#">About</nuxt-link></li>
      <li><nuxt-link to="/#">Works</nuxt-link></li>
      <li><nuxt-link to="/#">Contact</nuxt-link></li>
    </ul>
  </header>
</template>

<script lang="ts">
import Vue from 'vue';
export default Vue.extend({
  name: 'Header',
})
</script>

<style lang="scss" scoped>
#header {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 60px;
  z-index: 100;
  .menu {
    display: flex;
    justify-content: center;
    margin-top: 20px;
    margin-right: 10%;
    li {
      margin-left: 100px;
      font-size: 15px;
      font-weight: 900;
      font-family: 'Times New Roman', Times, serif;
      list-style: none;
      a {
        color: #555555;
        text-decoration: none;

        &:hover {
          color: #ff0000;
          border-bottom: 0.5px solid #ff0000;
          transition: 0.5s;
        }
      }
    }
  }
}
</style>

// src/components/Header.svelte
<script lang="ts">
  let isOpen: boolean = false;

  const toggleMenu = (): void => {
    isOpen = !isOpen;
  }
</script>

<style lang="scss">
  .menu {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.9);
    transform: scale(0);
    transition: transform 1s ease;
    display: flex;
    justify-content: center;
    align-items: center;
    color: #eee;
    z-index: 1;

    &.open {
      transform: scale(1);
    }

    ul {
      list-style: none;
      text-align: center;
      padding: 0;
      margin: 0;

      li {
        margin: 0;
        padding: 10px;
        a {
          color: #eee;
          text-decoration: none;
          font-size: 2rem;
          font-family: baskerville, serif;
          font-weight: bold;
          text-transform: uppercase;
          letter-spacing: 0.2rem;
          transition: color 0.3s ease;

          &:hover {
            color: #aaa;
          }
        }
      }
    }

  }

  .hamburger {
    position: absolute;
    top: 30px;
    right: 30px;
    cursor: pointer;
    filter: drop-shadow(0 0 2px rgba(0, 0, 0, 0.5));
    z-index: 2;

    .line {
      transition: all 0.3s ease;
    }

    &.open {
      .top {
        fill: white;
        transform: rotate(45deg) translate(10px, -15px);
      }

      .middle {
        opacity: 0;
      }

      .bottom {
        fill: white;
        transform: rotate(-45deg) translate(-30px, 15px);
      }
    }
  }
</style>

<div class="hamburger" class:open={isOpen} on:click={toggleMenu}>
  <svg viewBox="0 0 100 80" width="40" height="40">
    <rect class="line top" width="90" height="3" fill="#333" rx="5" ry="5"></rect>
    <rect class="line middle" y="20" width="90" height="3" fill="#333" rx="5" ry="5"></rect>
    <rect class="line bottom" y="40" width="90" height="3" fill="#333" rx="5" ry="5"></rect>
  </svg>
</div>

<div class="menu" class:open={isOpen} on:click={toggleMenu}>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
  </ul>
</div>
