// src/components/Header.vue
<template>
  <div>
    <header>
      <div class="menu-icon" @click="toggleMenu">
        <span></span>
        <span></span>
        <span></span>
      </div>
      <ul :class="{ open: menuOpen }">
        <li><a href="#about">About</a></li>
        <li><a href="#works">Works</a></li>
        <li><a href="#blog">Blog</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </header>
  </div>
</template>

<script>
export default {
  data() {
    return {
      menuOpen: false
    };
  },
  methods: {
    toggleMenu() {
      this.menuOpen = !this.menuOpen;
    }
  }
};
</script>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap');

header {
  position: fixed;
  padding: 20px 100px;
  display: flex;
  width: 100%;
  justify-content: flex-end;
  align-items: center;
  z-index: 100;
}

.menu-icon {
  display: none;
  flex-direction: column;
  cursor: pointer;
}

.menu-icon span {
  width: 30px;
  height: 3px;
  background-color: #eee;
  margin: 4px 0;
  transition: all 0.3s ease;
}

ul {
  display: flex;
  gap: 50px;
  padding: 0;
  margin: 0;
}

li {
  list-style: none;
}

a {
  text-decoration: none;
  font-family: 'Great Vibes', cursive;
  font-size: 24px;
  color: #eee;
  transition: color 0.3s ease, transform 0.3s ease;
}

a:hover {
  color: #ff6347;
  transform: scale(1.1);
}

@media (max-width: 768px) {
  header {
    padding: 20px;
  }

  .menu-icon {
    display: flex;
    opacity: 0.7;
    z-index: 10;
  }

  ul {
    position: fixed;
    top: 0;
    right: 0;
    flex-direction: column;
    background-color: #222;
    width: 100%;
    height: 100vh;
    transform: translateX(100%);
    transition: transform 0.5s ease;
    z-index: 9;
    overflow-y: auto;
  }

  ul.open {
    transform: translateX(0);
  }

  li {
    text-align: center;
    padding: 10px;
  }

  li:first-child {
    margin-top: 100px;
  }

  a {
    font-size: 24px;
  }
}
</style>

// src/components/Header.svelte
<script lang="ts">
  let isOpen: boolean = false;

  const toggleMenu = (): void => {
    isOpen = !isOpen;
  }
</script>

<style lang="scss">
  .menu {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.9);
    transform: scale(0);
    transition: transform 1s ease;
    display: flex;
    justify-content: center;
    align-items: center;
    color: #eee;
    z-index: 1;

    &.open {
      transform: scale(1);
    }

    ul {
      list-style: none;
      text-align: center;
      padding: 0;
      margin: 0;

      li {
        margin: 0;
        padding: 10px;
        a {
          color: #eee;
          text-decoration: none;
          font-size: 2rem;
          font-family: baskerville, serif;
          font-weight: bold;
          text-transform: uppercase;
          letter-spacing: 0.2rem;
          transition: color 0.3s ease;

          &:hover {
            color: #aaa;
          }
        }
      }
    }

  }

  .hamburger {
    position: absolute;
    top: 30px;
    right: 30px;
    cursor: pointer;
    filter: drop-shadow(0 0 2px rgba(0, 0, 0, 0.5));
    z-index: 2;

    .line {
      transition: all 0.3s ease;
    }

    &.open {
      .top {
        fill: white;
        transform: rotate(45deg) translate(10px, -15px);
      }

      .middle {
        opacity: 0;
      }

      .bottom {
        fill: white;
        transform: rotate(-45deg) translate(-30px, 15px);
      }
    }
  }
</style>

<div class="hamburger" class:open={isOpen} on:click={toggleMenu}>
  <svg viewBox="0 0 100 80" width="40" height="40">
    <rect class="line top" width="90" height="3" fill="#333" rx="5" ry="5"></rect>
    <rect class="line middle" y="20" width="90" height="3" fill="#333" rx="5" ry="5"></rect>
    <rect class="line bottom" y="40" width="90" height="3" fill="#333" rx="5" ry="5"></rect>
  </svg>
</div>

<div class="menu" class:open={isOpen} on:click={toggleMenu}>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About</a></li>
  </ul>
</div>
